### ISSUE TITLE
Missing saves

### ISSUE THREAD

**Issue by AceAzumarill** [TwitchPlaysPokemon/tpp-streamdocs#22]
There are multiple missing save files in the saves folder, such as the saves for Metronome Sapphire, NavyBlue, and Burning Red.

**Comment by red031000** [comment]
@m4-used-rollout BabyRage

**Comment by FrostedGeulleisia** [comment]
add the gauntlet to that RaccAttack

**Comment by Ravendwyr** [comment]
We can has Sirius? :3

**Comment by WhatAboutGaming** [comment]
M4 uploaded the files but forgot to close the issue https://github.com/TwitchPlaysPokemon/tpp-streamdocs/tree/master/saves
