### ISSUE TITLE
Sprite Credits missing

### ISSUE THREAD

**Issue by Felk** [TwitchPlaysPokemon/tpp-streamdocs#3]
Due to an error, the sprite credits were removed from the old description and are therefore missing now too.  They originally looked like this:

# Sprite credits

Sprites from Generation 5 and below are from [veekun.com/dex/downloads](https://veekun.com/dex/downloads).
Credits for the Generation 6 and 7 sprites, mainly used in "Who's that Pokemon?", can be found here:
- https://www.pokecommunity.com/showthread.php?t=314422
- https://www.pokecommunity.com/showthread.php?t=368703

**Comment by RedFlares** [comment]
Got it, will add these to the credits MD
